name: uni_track
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter:
  http: ^1.2.2
  file_picker: ^6.1.1
  path: ^1.9.0
  url_launcher: ^6.2.5
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  open_file: ^3.3.2
  image_gallery_saver_plus: 4.0.0
  bcrypt: ^1.1.3
  geolocator: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
   - images/
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
